_LANG = 'ko'

_STRINGS = {
    'ko': {
        'title':            '냠냠건강탐험대',
        'menu_start':       'SPACE / ENTER 로 시작',
        'menu_controls':    '점프: SPACE / ↑     슬라이드: ↓ / S',
        'menu_info':        '더블 점프 가능  |  HP 3개  |  P: 일시정지',
        'menu_skill_hint':  '냠냠게이지 모아서 Z키로 스킬 발동!',
        'menu_water_hint':  '생수를 마셔서 물게이지를 채우세요!',

        # 음식 도감
        'gallery_title':    '음식 도감',
        'gallery_hint':     'ESC 돌아가기   |   음식 위에 마우스를 올리면 효과가 표시돼요',
        'gallery_locked_hint': '게임에서 이 음식을 먹으면 잠금이 풀려요',
        'ach_title':        '업적 진행도',
        'ach_scroll_hint':  '↑ ↓ 스크롤    ESC 돌아가기',
        'ach_cat_a':        'A. 진행·거리',
        'ach_cat_b':        'B. 스테이지',
        'ach_cat_c':        'C. 콤보',
        'ach_cat_d':        'D. 음식 수집',
        'ach_cat_e':        'E. 음식 카테고리',
        'ach_cat_f':        'F. 회피·챌린지',
        'ach_cat_g':        'G. 물게이지',
        'ach_cat_h':        'H. HP·생존',
        'ach_cat_i':        'I. 스킬',
        'ach_cat_j':        'J. 점수',
        'attr_pos':         '긍정',
        'attr_neg':         '부정',
        'attr_neutral':     '무속성',
        'stage_school':     '학교',
        'stage_street':     '길거리',
        'stage_playground': '놀이터',
        'stage_home':       '집',
        'stage_all':        '전체',

        # 음식 이름
        'food_milk_name':                 '우유',
        'food_apple_name':                '사과',
        'food_kimbap_name':               '김밥',
        'food_cup_ramen_name':            '컵라면',
        'food_chocolate_name':            '초콜릿',
        'food_candy_name':                '사탕',
        'food_banana_milk_name':          '바나나우유',
        'food_triangle_kimbap_name':      '삼각김밥',
        'food_soy_milk_name':             '두유',
        'food_tteokbokki_name':           '떡볶이',
        'food_burger_name':               '햄버거',
        'food_slushie_name':              '슬러시',
        'food_cola_name':                 '콜라',
        'food_cherry_tomato_name':        '방울토마토',
        'food_fruit_juice_name':          '과일주스',
        'food_roasted_sweet_potato_name': '군고구마',
        'food_cotton_candy_name':         '솜사탕',
        'food_ice_cream_name':            '아이스크림',
        'food_rice_bowl_name':            '쌀밥',
        'food_seaweed_soup_name':         '미역국',
        'food_grilled_fish_name':         '생선구이',
        'food_instant_ramen_name':        '인스턴트라면',
        'food_pizza_name':                '배달피자',
        'food_snack_bag_name':            '봉지과자',
        'food_water_bottle_name':         '생수',

        'hud_score':        '점수',
        'hud_best':         '최고',
        'hud_speed':        '속도',
        'hud_pause_hint':   'P: 일시정지',
        'hud_shield':       '방어막',
        'hud_magnet':       '자석',
        'gauge_label':      '냠냠게이지',
        'gauge_activate':   'Z 발동!',
        'combo_label':      'COMBO',

        'countdown_go':     'GO!',

        'pause_title':      '일시정지',
        'pause_continue':   'P : 계속하기',
        'pause_menu':       'ESC : 메뉴로 돌아가기',

        'gameover_title':   '게임 오버',
        'gameover_score':   '점수',
        'gameover_dist':    '달린 거리',
        'gameover_new_best':'NEW BEST!',
        'gameover_high':    '최고 기록',
        'gameover_hint':    'SPACE / ENTER: 재시작   |   ESC: 메뉴',

        'settings_title':   '설정',
        'settings_bgm':     'BGM 음량',
        'settings_sfx':     '효과음 음량',
        'settings_lang':    '언어',
        'settings_hint':    '← →  조절 / 선택    ↑ ↓  이동    ESC  돌아가기',

        'lang_ko':          '한국어',
        'lang_en':          'English',
        'lang_vi':          'Tiếng Việt',

        'gameinfo_title':   '게임 정보',
        'gi_dev_title':     '개발자 정보',
        'gi_game_name_lbl': '게임 이름',
        'gi_game_name_val': '냠냠건강탐험대',
        'gi_version_lbl':   '버전',
        'gi_version_val':   'v1.0',
        'gi_dev_lbl':       '개발',
        'gi_dev_val':       '이소희',
        'gi_tool_lbl':      '제작 도구',
        'gi_tool_val':      'Python  +  pygame-ce',
        'gi_team_title':    '팀 소개',
        'gi_team_intro': (
            "안녕하세요. 저희는 서울여자대학교 바롬설계프로젝트 4조 '올바롬'입니다.\n\n"
            "'올바롬'은 아동·청소년의 건강한 성장과 정서적 안정을 돕고자 모인 팀입니다. "
            "다양한 전공을 가진 6명의 대학생이 각자의 아이디어와 전문성을 바탕으로, "
            "아이들이 더 나은 생활 습관을 자연스럽게 경험할 수 있는 방향을 함께 고민하고 있습니다.\n\n"
            "감사합니다."
        ),
        'gi_team_members_title': '팀원 소개',
        # 팀원별 소개
        'teammate_naeyoung_intro': '안녕 나는 내영이야!\n우리 함께 건강한 식습관을 차근차근 만들어가 보자~',
        'teammate_seoha_intro':    '안녕 나는 올바롬 팀의 팀장 서하야!\n같이 꾸준히 식습관 길러보자!',
        'teammate_seohyeon_intro': '안녕 나는 서현이야!\n건강한 음식을 잘 골라서 완주 하길 바랄게~!!',
        'teammate_sumin_intro':    '안녕 나는 수민이야!\n나쁜 젤리를 잘 피해보도록 하자~',
        'teammate_tutao_intro':    '안녕! 나는 투타오야^ㅡ^',
        'easter_egg_reset':  '✨ 데이터가 모두 초기화되었어요! ✨',
        'easter_egg_outfit': '🎽 교복 색깔이 바뀌었어요! 🎽',
        'gi_purpose_title': '게임 개발 목적',
        'gi_purpose_text': (
            "본 게임은 아이들이 올바른 먹거리 습관을 쉽고 즐겁게 배울 수 있도록 개발되었습니다.\n\n"
            "아동·청소년이 게임을 플레이하는 과정에서 건강한 음식과 그렇지 않은 음식의 차이를 "
            "자연스럽게 인식하고, 일상생활 속에서 스스로 더 건강한 선택을 할 수 있도록 돕는 것을 "
            "목표로 합니다.\n\n"
            "또한 단순한 정보 전달이 아닌, 직접 참여하고 경험하는 방식의 교육을 통해 아이들이 "
            "부담 없이 건강한 식습관의 중요성을 이해할 수 있도록 기획하였습니다."
        ),
        'gi_font_title':    '폰트 저작권',
        'gi_font_lbl':      '폰트',
        'gi_font_val':      '학교안심 시간표 R',
        'gi_author_lbl':    '저작자',
        'gi_author_val':    'Tlab신영복체  /  박윤정엔타이포랩',
        'gi_source_lbl':    '출처',
        'gi_source_val':    '공유마당',
        'gi_license_lbl':   '라이선스',
        'gi_license_val':   'OFL (Open Font License)',
        'gi_font2_lbl':     '베트남어 폰트',
        'gi_font2_val':     'Quicksand',
        'gi_author2_lbl':   '저작자',
        'gi_author2_val':   'Andrew Paglinawan',
        'gi_source2_lbl':   '출처',
        'gi_source2_val':   'Google Fonts',
        'gi_license2_lbl':  '라이선스',
        'gi_license2_val':  'OFL (Open Font License)',
        'gi_scroll_hint':   '↑ ↓ 스크롤    ESC 돌아가기',

        'ach_popup_label':  '칭찬스티커',

        'ach_first_run_name':        '첫 출석',
        'ach_first_run_desc':        '게임을 처음 시작했어요!',
        'ach_dist_100_name':         '100m 달성',
        'ach_dist_100_desc':         '100m를 달렸어요!',
        'ach_dist_500_name':         '500m 달성',
        'ach_dist_500_desc':         '500m를 달렸어요!',
        'ach_dist_1000_name':        '1000m 달성',
        'ach_dist_1000_desc':        '1000m를 달렸어요!',
        'ach_jelly_50_name':         '젤리 수집왕',
        'ach_jelly_50_desc':         '한 판에 젤리 50개를 모았어요!',
        'ach_combo_30_name':         '콤보 마스터',
        'ach_combo_30_desc':         '30콤보를 달성했어요!',
        'ach_stage_street_name':     '길거리 도착',
        'ach_stage_street_desc':     '길거리 스테이지에 도착했어요!',
        'ach_stage_playground_name': '놀이터 도착',
        'ach_stage_playground_desc': '놀이터 스테이지에 도착했어요!',
        'ach_stage_home_name':       '귀가 완료',
        'ach_stage_home_desc':       '집 스테이지에 도착했어요!',
        'ach_shield_block_name':     '무적 용사',
        'ach_shield_block_desc':     '방어막으로 장애물을 막았어요!',

        # 신규 업적 (40개)
        'ach_dist_2000_name':        '2km 돌파',
        'ach_dist_2000_desc':        '2,000m를 달렸어요!',
        'ach_dist_3000_name':        '3km 마라토너',
        'ach_dist_3000_desc':        '3,000m를 달렸어요!',
        'ach_dist_5000_name':        '장거리 주자',
        'ach_dist_5000_desc':        '5,000m를 달렸어요!',
        'ach_dist_10000_name':       '전설의 주자',
        'ach_dist_10000_desc':       '10,000m를 달렸어요!',
        'ach_stage_loop_name':       '학교로 귀환',
        'ach_stage_loop_desc':       '한 게임에서 집을 거쳐 학교로 돌아왔어요!',
        'ach_all_stages_name':       '사방 탐험가',
        'ach_all_stages_desc':       '한 게임에서 4스테이지를 모두 방문했어요!',
        'ach_combo_10_name':         '첫 콤보',
        'ach_combo_10_desc':         '10콤보를 달성했어요!',
        'ach_combo_50_name':         '콤보 챔피언',
        'ach_combo_50_desc':         '50콤보를 달성했어요!',
        'ach_combo_100_name':        '콤보 전설',
        'ach_combo_100_desc':        '100콤보를 달성했어요!',
        'ach_max_multiplier_name':   '4배율 달성',
        'ach_max_multiplier_desc':   '점수 배율 4배에 도달했어요!',
        'ach_food_100_run_name':     '폭식 챔피언',
        'ach_food_100_run_desc':     '한 게임에 음식 100개를 모았어요!',
        'ach_positive_30_name':      '건강 미식가',
        'ach_positive_30_desc':      '한 게임에 건강한 음식 30개를 먹었어요!',
        'ach_school_master_name':    '학교 마스터',
        'ach_school_master_desc':    '학교 건강 음식 3종을 모두 먹었어요!',
        'ach_street_master_name':    '편의점 마스터',
        'ach_street_master_desc':    '길거리 건강 음식 3종을 모두 먹었어요!',
        'ach_playground_master_name':'간식 마스터',
        'ach_playground_master_desc':'놀이터 건강 음식 3종을 모두 먹었어요!',
        'ach_home_master_name':      '집밥 마스터',
        'ach_home_master_desc':      '집 건강 음식 3종을 모두 먹었어요!',
        'ach_all_pos_master_name':   '완벽한 식단',
        'ach_all_pos_master_desc':   '한 게임에 건강 음식 12종을 모두 먹었어요!',
        'ach_veggie_lover_name':     '채소·과일 친구',
        'ach_veggie_lover_desc':     '사과·방울토마토·군고구마를 모두 먹었어요!',
        'ach_protein_set_name':      '단백질 조합',
        'ach_protein_set_desc':      '우유·두유·생선구이를 모두 먹었어요!',
        'ach_pure_run_name':         '깨끗한 식단',
        'ach_pure_run_desc':         '나쁜 음식 0개로 1,000m를 달렸어요!',
        'ach_no_cola_name':          '노콜라 챌린지',
        'ach_no_cola_desc':          '콜라 0개로 1,000m를 달렸어요!',
        'ach_junk_avoider_name':     '정크 회피자',
        'ach_junk_avoider_desc':     '햄버거·피자·라면·콜라 안 먹고 1,000m!',
        'ach_snack_avoider_name':    '단 음식 거부',
        'ach_snack_avoider_desc':    '사탕·솜사탕·아이스크림·초콜릿 안 먹고 500m!',
        'ach_water_first_name':      '첫 수분 보충',
        'ach_water_first_desc':      '생수를 처음 마셨어요!',
        'ach_water_5_run_name':      '수분 충전',
        'ach_water_5_run_desc':      '한 게임에 생수 5개를 마셨어요!',
        'ach_water_10_run_name':     '수분 박사',
        'ach_water_10_run_desc':     '한 게임에 생수 10개를 마셨어요!',
        'ach_hydration_master_name': '수분 균형',
        'ach_hydration_master_desc': '1,000m 동안 물게이지 50% 이상을 유지했어요!',
        'ach_thirst_survive_name':   '갈증 극복',
        'ach_thirst_survive_desc':   '갈증 상태에서 100m를 추가로 달렸어요!',
        'ach_hp_full_500_name':      '무사 통과',
        'ach_hp_full_500_desc':      'HP 만피로 500m를 달렸어요!',
        'ach_last_breath_name':      '마지막 숨',
        'ach_last_breath_desc':      'HP 1로 100m를 추가로 달렸어요!',
        'ach_heart_collector_name':  '하트 수집가',
        'ach_heart_collector_desc':  '한 게임에 하트 3개를 모았어요!',
        'ach_first_skill_name':      '첫 스킬',
        'ach_first_skill_desc':      '스킬을 처음 발동했어요!',
        'ach_skill_master_name':     '스킬 마스터',
        'ach_skill_master_desc':     '한 게임에 스킬 5번을 발동했어요!',
        'ach_invincible_clear_name': '무적 돌파',
        'ach_invincible_clear_desc': '무적 스킬로 장애물을 그냥 지나갔어요!',
        'ach_all_skills_name':       '4스킬 컬렉터',
        'ach_all_skills_desc':       '한 게임에 4종 스킬을 모두 발동했어요!',
        'ach_shield_perfect_name':   '방어막 절약',
        'ach_shield_perfect_desc':   '방어막을 켠 채 1,000m를 달렸어요!',
        'ach_score_5000_name':       '5천점 돌파',
        'ach_score_5000_desc':       '5,000점을 달성했어요!',
        'ach_score_20000_name':      '2만점 돌파',
        'ach_score_20000_desc':      '20,000점을 달성했어요!',
        'ach_score_50000_name':      '5만점 마스터',
        'ach_score_50000_desc':      '50,000점을 달성했어요!',
        'ach_new_record_name':       '신기록!',
        'ach_new_record_desc':       '최고 기록을 갱신했어요!',

        'skill_invincible_name':  '무적 질주!',
        'skill_slowdown_name':    '시간 감속!',
        'skill_jelly_party_name': '젤리 파티!',
        'skill_score_blast_name': '점수 폭발!',

        # 음식 효과 — 팝업 짧은 이름
        'effect_hp_or_score_short':  'HP +1',
        'effect_combo_plus_short':   '콤보 +3',
        'effect_gauge_l_short':      '게이지 +20',
        'effect_gauge_s_short':      '게이지 +15',
        'effect_gauge_drain_short':  '게이지 -25',
        'effect_magnet_short_short': '자석 효과!',
        'effect_score_bonus_short':  '점수 보너스!',
        'effect_score_l_short':      '점수 대박!',
        'effect_rice_combo_short':   '쌀밥 보너스',
        'effect_hp_chance_short':    'HP 회복!',
        'effect_shield_grant_short': '방어막 획득!',
        'effect_cleanse_short':      '디버프 해제!',
        'effect_combo_break_short':  '콤보 끊김',
        'effect_water_refill_short': '물 +20',
        'effect_water_drain_short':  '물 -15',
        'effect_dizzy_short':        '어지러움 (더블점프 봉인)',
        'effect_heavy_jump_short':   '점프력 ↓',
        'effect_heavy_jump_l_short': '점프력 ↓',
        'effect_heavy_combo_short':  '점프 ↓ + 콤보 정지',
        'effect_vision_blur_short':  '시야 좁힘',
        'effect_slow_freeze_short':  '얼음 감속',
        'effect_sticky_short':       '끈적임 (슬라이드 봉인)',
        'effect_slide_short_short':  '슬라이드 ↓',
        'effect_gauge_freeze_short': '게이지 정지',
        'effect_score_mult_short':   '점수 ×1.5!',
    },

    'en': {
        'title':            'Yum Yum Health Explorer',
        'menu_start':       'Press SPACE / ENTER to Start',
        'menu_controls':    'Jump: SPACE / ↑     Slide: ↓ / S',
        'menu_info':        'Double Jump  |  3 HP  |  P: Pause',
        'menu_skill_hint':  'Fill gauge and press Z to activate skill!',
        'menu_water_hint':  'Drink bottled water to keep your hydration up!',

        # Food gallery
        'gallery_title':    'Food Gallery',
        'gallery_hint':     'ESC to go back   |   Hover over a food to see its effect',
        'gallery_locked_hint': 'Eat this food in-game to unlock it',
        'ach_title':        'Achievements',
        'ach_scroll_hint':  '↑ ↓ Scroll    ESC Back',
        'ach_cat_a':        'A. Distance',
        'ach_cat_b':        'B. Stages',
        'ach_cat_c':        'C. Combo',
        'ach_cat_d':        'D. Food Collection',
        'ach_cat_e':        'E. Food Categories',
        'ach_cat_f':        'F. Avoidance',
        'ach_cat_g':        'G. Hydration',
        'ach_cat_h':        'H. HP / Survival',
        'ach_cat_i':        'I. Skills',
        'ach_cat_j':        'J. Score',
        'attr_pos':         'Healthy',
        'attr_neg':         'Unhealthy',
        'attr_neutral':     'Neutral',
        'stage_school':     'School',
        'stage_street':     'Street',
        'stage_playground': 'Playground',
        'stage_home':       'Home',
        'stage_all':        'All',

        # Food names
        'food_milk_name':                 'Milk',
        'food_apple_name':                'Apple',
        'food_kimbap_name':               'Kimbap',
        'food_cup_ramen_name':            'Cup Ramen',
        'food_chocolate_name':            'Chocolate',
        'food_candy_name':                'Candy',
        'food_banana_milk_name':          'Banana Milk',
        'food_triangle_kimbap_name':      'Triangle Kimbap',
        'food_soy_milk_name':             'Soy Milk',
        'food_tteokbokki_name':           'Tteokbokki',
        'food_burger_name':               'Burger',
        'food_slushie_name':              'Slushie',
        'food_cola_name':                 'Cola',
        'food_cherry_tomato_name':        'Cherry Tomato',
        'food_fruit_juice_name':          'Fruit Juice',
        'food_roasted_sweet_potato_name': 'Roasted Sweet Potato',
        'food_cotton_candy_name':         'Cotton Candy',
        'food_ice_cream_name':            'Ice Cream',
        'food_rice_bowl_name':            'Rice Bowl',
        'food_seaweed_soup_name':         'Seaweed Soup',
        'food_grilled_fish_name':         'Grilled Fish',
        'food_instant_ramen_name':        'Instant Ramen',
        'food_pizza_name':                'Delivery Pizza',
        'food_snack_bag_name':            'Snack Bag',
        'food_water_bottle_name':         'Bottled Water',

        'hud_score':        'Score',
        'hud_best':         'Best',
        'hud_speed':        'Speed',
        'hud_pause_hint':   'P: Pause',
        'hud_shield':       'Shield',
        'hud_magnet':       'Magnet',
        'gauge_label':      'Energy Gauge',
        'gauge_activate':   'Press Z!',
        'combo_label':      'COMBO',

        'countdown_go':     'GO!',

        'pause_title':      'Paused',
        'pause_continue':   'P : Continue',
        'pause_menu':       'ESC : Back to Menu',

        'gameover_title':   'Game Over',
        'gameover_score':   'Score',
        'gameover_dist':    'Distance',
        'gameover_new_best':'NEW BEST!',
        'gameover_high':    'High Score',
        'gameover_hint':    'SPACE / ENTER: Restart   |   ESC: Menu',

        'settings_title':   'Settings',
        'settings_bgm':     'BGM Volume',
        'settings_sfx':     'SFX Volume',
        'settings_lang':    'Language',
        'settings_hint':    '← →  Adjust / Select    ↑ ↓  Move    ESC  Back',

        'lang_ko':          '한국어',
        'lang_en':          'English',
        'lang_vi':          'Tiếng Việt',

        'gameinfo_title':   'Game Info',
        'gi_dev_title':     'Developer Info',
        'gi_game_name_lbl': 'Game Title',
        'gi_game_name_val': 'Yum Yum Health Explorer',
        'gi_version_lbl':   'Version',
        'gi_version_val':   'v1.0',
        'gi_dev_lbl':       'Developer',
        'gi_dev_val':       'Lee Sohee',
        'gi_tool_lbl':      'Built With',
        'gi_tool_val':      'Python  +  pygame-ce',
        'gi_team_title':    'Our Team',
        'gi_team_intro': (
            "Hello! We are Team 'Olbarom', Group 4 of the Barom Design Project at Seoul Women's University.\n\n"
            "'Olbarom' is a team dedicated to supporting the healthy growth and emotional well-being of children and youth. "
            "Six college students from diverse majors are working together — drawing on their own ideas and expertise — "
            "to help children naturally develop better lifestyle habits.\n\n"
            "Thank you."
        ),
        'gi_team_members_title': 'Team Members',
        # Per-teammate intros
        'teammate_naeyoung_intro': "Hi, I'm Naeyoung!\nLet's build healthy eating habits together, step by step~",
        'teammate_seoha_intro':    "Hi, I'm Seoha, the leader of Team Olbarom!\nLet's keep building healthy habits together!",
        'teammate_seohyeon_intro': "Hi, I'm Seohyeon!\nHope you pick the healthy foods and finish strong~!!",
        'teammate_sumin_intro':    "Hi, I'm Sumin!\nLet's dodge those bad jellies~",
        'teammate_tutao_intro':    "Hi! I'm Tutao ^ㅡ^",
        'easter_egg_reset':  '✨ All progress has been reset! ✨',
        'easter_egg_outfit': '🎽 Uniform color changed! 🎽',
        'gi_purpose_title': 'Game Purpose',
        'gi_purpose_text': (
            "This game was developed to help children learn healthy eating habits in a fun and engaging way.\n\n"
            "Our goal is for children and youth to naturally recognize the difference between healthy and unhealthy foods "
            "as they play, and to feel empowered to make healthier choices in their daily lives.\n\n"
            "Rather than simply delivering information, we designed this game as an interactive, experiential form of education — "
            "so children can understand the importance of healthy eating habits without any pressure."
        ),
        'gi_font_title':    'Font Copyright',
        'gi_font_lbl':      'Font',
        'gi_font_val':      'Hakgyoansim Siganpyo R',
        'gi_author_lbl':    'Author',
        'gi_author_val':    'Tlab Shin Youngbok  /  Park Yunjung ENTypoLab',
        'gi_source_lbl':    'Source',
        'gi_source_val':    'Gong Yu Madang',
        'gi_license_lbl':   'License',
        'gi_license_val':   'OFL (Open Font License)',
        'gi_font2_lbl':     'Vietnamese Font',
        'gi_font2_val':     'Quicksand',
        'gi_author2_lbl':   'Author',
        'gi_author2_val':   'Andrew Paglinawan',
        'gi_source2_lbl':   'Source',
        'gi_source2_val':   'Google Fonts',
        'gi_license2_lbl':  'License',
        'gi_license2_val':  'OFL (Open Font License)',
        'gi_scroll_hint':   '↑ ↓ Scroll    ESC Back',

        'ach_popup_label':  'Achievement!',

        'ach_first_run_name':        'First Visit',
        'ach_first_run_desc':        'Started the game for the first time!',
        'ach_dist_100_name':         '100m Reached',
        'ach_dist_100_desc':         'You ran 100 meters!',
        'ach_dist_500_name':         '500m Reached',
        'ach_dist_500_desc':         'You ran 500 meters!',
        'ach_dist_1000_name':        '1000m Reached',
        'ach_dist_1000_desc':        'You ran 1000 meters!',
        'ach_jelly_50_name':         'Jelly Collector',
        'ach_jelly_50_desc':         'Collected 50 jellies in one run!',
        'ach_combo_30_name':         'Combo Master',
        'ach_combo_30_desc':         'Achieved a 30-combo!',
        'ach_stage_street_name':     'On the Street',
        'ach_stage_street_desc':     'Reached the street stage!',
        'ach_stage_playground_name': 'At the Playground',
        'ach_stage_playground_desc': 'Reached the playground stage!',
        'ach_stage_home_name':       'Back Home',
        'ach_stage_home_desc':       'Reached the home stage!',
        'ach_shield_block_name':     'Brave Warrior',
        'ach_shield_block_desc':     'Blocked an obstacle with a shield!',

        # New achievements (40)
        'ach_dist_2000_name':        '2km Cleared',
        'ach_dist_2000_desc':        'You ran 2,000 meters!',
        'ach_dist_3000_name':        '3km Marathoner',
        'ach_dist_3000_desc':        'You ran 3,000 meters!',
        'ach_dist_5000_name':        'Long Distance Runner',
        'ach_dist_5000_desc':        'You ran 5,000 meters!',
        'ach_dist_10000_name':       'Legendary Runner',
        'ach_dist_10000_desc':       'You ran 10,000 meters!',
        'ach_stage_loop_name':       'Back to School',
        'ach_stage_loop_desc':       'Returned to school via home in one run!',
        'ach_all_stages_name':       'Four-Way Explorer',
        'ach_all_stages_desc':       'Visited all 4 stages in one run!',
        'ach_combo_10_name':         'First Combo',
        'ach_combo_10_desc':         'Achieved a 10-combo!',
        'ach_combo_50_name':         'Combo Champion',
        'ach_combo_50_desc':         'Achieved a 50-combo!',
        'ach_combo_100_name':        'Combo Legend',
        'ach_combo_100_desc':        'Achieved a 100-combo!',
        'ach_max_multiplier_name':   '4× Multiplier',
        'ach_max_multiplier_desc':   'Reached 4× score multiplier!',
        'ach_food_100_run_name':     'Big Eater',
        'ach_food_100_run_desc':     'Collected 100 foods in one run!',
        'ach_positive_30_name':      'Healthy Gourmet',
        'ach_positive_30_desc':      'Ate 30 healthy foods in one run!',
        'ach_school_master_name':    'School Master',
        'ach_school_master_desc':    'Ate all 3 healthy school foods!',
        'ach_street_master_name':    'Convenience Master',
        'ach_street_master_desc':    'Ate all 3 healthy street foods!',
        'ach_playground_master_name':'Snack Master',
        'ach_playground_master_desc':'Ate all 3 healthy playground foods!',
        'ach_home_master_name':      'Home Cooking Master',
        'ach_home_master_desc':      'Ate all 3 healthy home foods!',
        'ach_all_pos_master_name':   'Perfect Diet',
        'ach_all_pos_master_desc':   'Ate all 12 healthy foods in one run!',
        'ach_veggie_lover_name':     'Veggie & Fruit Friend',
        'ach_veggie_lover_desc':     'Ate apple, cherry tomato, sweet potato!',
        'ach_protein_set_name':      'Protein Combo',
        'ach_protein_set_desc':      'Ate milk, soy milk, grilled fish!',
        'ach_pure_run_name':         'Clean Diet',
        'ach_pure_run_desc':         'Ran 1,000m with zero unhealthy foods!',
        'ach_no_cola_name':          'No Cola Challenge',
        'ach_no_cola_desc':          'Ran 1,000m without drinking cola!',
        'ach_junk_avoider_name':     'Junk Avoider',
        'ach_junk_avoider_desc':     'Ran 1,000m without burger/pizza/ramen/cola!',
        'ach_snack_avoider_name':    'Sweet Refuser',
        'ach_snack_avoider_desc':    'Ran 500m without candy/cotton/ice cream/chocolate!',
        'ach_water_first_name':      'First Sip',
        'ach_water_first_desc':      'Drank bottled water for the first time!',
        'ach_water_5_run_name':      'Hydration Boost',
        'ach_water_5_run_desc':      'Drank 5 bottles of water in one run!',
        'ach_water_10_run_name':     'Hydration Expert',
        'ach_water_10_run_desc':     'Drank 10 bottles of water in one run!',
        'ach_hydration_master_name': 'Hydration Balance',
        'ach_hydration_master_desc': 'Kept water gauge ≥50% for 1,000m!',
        'ach_thirst_survive_name':   'Thirst Survivor',
        'ach_thirst_survive_desc':   'Ran 100m more while thirsty!',
        'ach_hp_full_500_name':      'Untouched',
        'ach_hp_full_500_desc':      'Ran 500m at full HP!',
        'ach_last_breath_name':      'Last Breath',
        'ach_last_breath_desc':      'Ran 100m more with only 1 HP!',
        'ach_heart_collector_name':  'Heart Collector',
        'ach_heart_collector_desc':  'Collected 3 hearts in one run!',
        'ach_first_skill_name':      'First Skill',
        'ach_first_skill_desc':      'Activated a skill for the first time!',
        'ach_skill_master_name':     'Skill Master',
        'ach_skill_master_desc':     'Activated 5 skills in one run!',
        'ach_invincible_clear_name': 'Invincible Pass',
        'ach_invincible_clear_desc': 'Passed through an obstacle while invincible!',
        'ach_all_skills_name':       'Skill Collector',
        'ach_all_skills_desc':       'Activated all 4 skill types in one run!',
        'ach_shield_perfect_name':   'Shield Saver',
        'ach_shield_perfect_desc':   'Ran 1,000m with shield active!',
        'ach_score_5000_name':       '5,000 Points',
        'ach_score_5000_desc':       'Reached 5,000 points!',
        'ach_score_20000_name':      '20,000 Points',
        'ach_score_20000_desc':      'Reached 20,000 points!',
        'ach_score_50000_name':      '50,000 Points Master',
        'ach_score_50000_desc':      'Reached 50,000 points!',
        'ach_new_record_name':       'New Record!',
        'ach_new_record_desc':       'Set a new high score!',

        'skill_invincible_name':  'Invincible!',
        'skill_slowdown_name':    'Slow Time!',
        'skill_jelly_party_name': 'Jelly Party!',
        'skill_score_blast_name': 'Score Blast!',

        # Food effects — popup short names
        'effect_hp_or_score_short':  'HP +1',
        'effect_combo_plus_short':   'Combo +3',
        'effect_gauge_l_short':      'Gauge +20',
        'effect_gauge_s_short':      'Gauge +15',
        'effect_gauge_drain_short':  'Gauge -25',
        'effect_magnet_short_short': 'Magnet!',
        'effect_score_bonus_short':  'Score Bonus!',
        'effect_score_l_short':      'Big Score!',
        'effect_rice_combo_short':   'Rice Bonus',
        'effect_hp_chance_short':    'HP Healed!',
        'effect_shield_grant_short': 'Shield!',
        'effect_cleanse_short':      'Cleansed!',
        'effect_combo_break_short':  'Combo Broken',
        'effect_water_refill_short': 'Water +20',
        'effect_water_drain_short':  'Water -15',
        'effect_dizzy_short':        'Dizzy (No Double Jump)',
        'effect_heavy_jump_short':   'Jump ↓',
        'effect_heavy_jump_l_short': 'Jump ↓',
        'effect_heavy_combo_short':  'Jump ↓ + Combo Frozen',
        'effect_vision_blur_short':  'Vision Blur',
        'effect_slow_freeze_short':  'Frozen Slow',
        'effect_sticky_short':       'Sticky (No Slide)',
        'effect_slide_short_short':  'Slide ↓',
        'effect_gauge_freeze_short': 'Gauge Frozen',
        'effect_score_mult_short':   'Score ×1.5!',
    },

    'vi': {
        'title':            'Đội Thám Hiểm Sức Khỏe',
        'menu_start':       'Nhấn SPACE / ENTER để bắt đầu',
        'menu_controls':    'Nhảy: SPACE / W     Trượt: S',
        'menu_info':        'Nhảy đôi  |  3 HP  |  P: Dừng',
        'menu_skill_hint':  'Tích đủ năng lượng, nhấn Z để dùng kỹ năng!',
        'menu_water_hint':  'Uống nước để giữ thanh nước đầy!',

        # Bộ sưu tập món ăn
        'gallery_title':    'Bộ Sưu Tập Món Ăn',
        'gallery_hint':     'ESC để quay lại   |   Di chuột vào món ăn để xem hiệu ứng',
        'gallery_locked_hint': 'Ăn món này trong game để mở khóa',
        'ach_title':        'Thành Tựu',
        'ach_scroll_hint':  'W / S Cuộn    ESC Quay lại',
        'ach_cat_a':        'A. Khoảng cách',
        'ach_cat_b':        'B. Sân chơi',
        'ach_cat_c':        'C. Combo',
        'ach_cat_d':        'D. Sưu tầm món ăn',
        'ach_cat_e':        'E. Nhóm món ăn',
        'ach_cat_f':        'F. Né tránh',
        'ach_cat_g':        'G. Nước uống',
        'ach_cat_h':        'H. HP / Sinh tồn',
        'ach_cat_i':        'I. Kỹ năng',
        'ach_cat_j':        'J. Điểm số',
        'attr_pos':         'Lành mạnh',
        'attr_neg':         'Không lành mạnh',
        'attr_neutral':     'Trung tính',
        'stage_school':     'Trường',
        'stage_street':     'Đường phố',
        'stage_playground': 'Sân chơi',
        'stage_home':       'Nhà',
        'stage_all':        'Tất cả',

        # Tên món ăn
        'food_milk_name':                 'Sữa',
        'food_apple_name':                'Táo',
        'food_kimbap_name':               'Kimbap',
        'food_cup_ramen_name':            'Mì cốc',
        'food_chocolate_name':            'Sô cô la',
        'food_candy_name':                'Kẹo',
        'food_banana_milk_name':          'Sữa chuối',
        'food_triangle_kimbap_name':      'Cơm nắm',
        'food_soy_milk_name':             'Sữa đậu nành',
        'food_tteokbokki_name':           'Tteokbokki',
        'food_burger_name':               'Hamburger',
        'food_slushie_name':              'Slushie',
        'food_cola_name':                 'Coca',
        'food_cherry_tomato_name':        'Cà chua bi',
        'food_fruit_juice_name':          'Nước ép trái cây',
        'food_roasted_sweet_potato_name': 'Khoai lang nướng',
        'food_cotton_candy_name':         'Kẹo bông',
        'food_ice_cream_name':            'Kem',
        'food_rice_bowl_name':            'Cơm trắng',
        'food_seaweed_soup_name':         'Canh rong biển',
        'food_grilled_fish_name':         'Cá nướng',
        'food_instant_ramen_name':        'Mì gói',
        'food_pizza_name':                'Pizza giao hàng',
        'food_snack_bag_name':            'Bim bim',
        'food_water_bottle_name':         'Nước đóng chai',

        'hud_score':        'Điểm',
        'hud_best':         'Cao nhất',
        'hud_speed':        'Tốc độ',
        'hud_pause_hint':   'P: Dừng',
        'hud_shield':       'Lá chắn',
        'hud_magnet':       'Nam châm',
        'gauge_label':      'Thanh năng lượng',
        'gauge_activate':   'Nhấn Z!',
        'combo_label':      'COMBO',

        'countdown_go':     'BẮT ĐẦU!',

        'pause_title':      'Tạm dừng',
        'pause_continue':   'P : Tiếp tục',
        'pause_menu':       'ESC : Về menu',

        'gameover_title':   'Kết thúc',
        'gameover_score':   'Điểm',
        'gameover_dist':    'Khoảng cách',
        'gameover_new_best':'KỶ LỤC MỚI!',
        'gameover_high':    'Điểm cao nhất',
        'gameover_hint':    'SPACE / ENTER: Chơi lại   |   ESC: Menu',

        'settings_title':   'Cài đặt',
        'settings_bgm':     'Nhạc nền',
        'settings_sfx':     'Hiệu ứng',
        'settings_lang':    'Ngôn ngữ',
        'settings_hint':    'A / D  Điều chỉnh / Chọn    W / S  Di chuyển    ESC  Quay lại',

        'lang_ko':          '한국어',
        'lang_en':          'English',
        'lang_vi':          'Tiếng Việt',

        'gameinfo_title':   'Thông tin',
        'gi_dev_title':     'Thông tin nhà phát triển',
        'gi_game_name_lbl': 'Tên game',
        'gi_game_name_val': 'Đội Thám Hiểm Sức Khỏe',
        'gi_version_lbl':   'Phiên bản',
        'gi_version_val':   'v1.0',
        'gi_dev_lbl':       'Nhà phát triển',
        'gi_dev_val':       'Lee Sohee',
        'gi_tool_lbl':      'Công cụ',
        'gi_tool_val':      'Python  +  pygame-ce',
        'gi_team_title':    'Giới thiệu nhóm',
        'gi_team_intro': (
            "Xin chào! Chúng tôi là nhóm 'Olbarom', nhóm 4 của Dự án Thiết kế Barom tại Đại học Nữ Seoul.\n\n"
            "'Olbarom' là nhóm được thành lập với mục tiêu hỗ trợ sự phát triển lành mạnh và ổn định cảm xúc của trẻ em và thanh thiếu niên. "
            "Sáu sinh viên từ nhiều chuyên ngành khác nhau đang cùng nhau tư duy — dựa trên ý tưởng và chuyên môn của mỗi người — "
            "để giúp trẻ em tự nhiên hình thành những thói quen sống tốt hơn.\n\n"
            "Xin cảm ơn."
        ),
        'gi_team_members_title': 'Thành viên nhóm',
        # Giới thiệu từng thành viên
        'teammate_naeyoung_intro': 'Xin chào, mình là Naeyoung!\nCùng nhau xây dựng thói quen ăn uống lành mạnh từng bước nhé~',
        'teammate_seoha_intro':    'Xin chào, mình là Seoha — trưởng nhóm Olbarom!\nCùng nhau duy trì thói quen ăn uống lành mạnh nhé!',
        'teammate_seohyeon_intro': 'Xin chào, mình là Seohyeon!\nMong bạn chọn được món lành mạnh và về đích~!!',
        'teammate_sumin_intro':    'Xin chào, mình là Sumin!\nCùng nhau né những viên jelly xấu nhé~',
        'teammate_tutao_intro':    'Xin chào! Mình là Tutao ^ㅡ^',
        'easter_egg_reset':  '✨ Mọi tiến trình đã được đặt lại! ✨',
        'easter_egg_outfit': '🎽 Màu đồng phục đã thay đổi! 🎽',
        'gi_purpose_title': 'Mục đích phát triển',
        'gi_purpose_text': (
            "Game này được phát triển để giúp trẻ em học thói quen ăn uống lành mạnh một cách dễ dàng và thú vị.\n\n"
            "Mục tiêu của chúng tôi là giúp trẻ em và thanh thiếu niên tự nhiên nhận ra sự khác biệt giữa thực phẩm lành mạnh "
            "và không lành mạnh trong quá trình chơi game, từ đó tự mình có thể lựa chọn lành mạnh hơn trong cuộc sống hàng ngày.\n\n"
            "Thay vì chỉ truyền đạt thông tin, chúng tôi thiết kế game như một hình thức giáo dục tương tác, trải nghiệm — "
            "để trẻ em có thể hiểu tầm quan trọng của thói quen ăn uống lành mạnh mà không cảm thấy áp lực."
        ),
        'gi_font_title':    'Bản quyền phông chữ',
        'gi_font_lbl':      'Phông chữ',
        'gi_font_val':      'Hakgyoansim Siganpyo R',
        'gi_author_lbl':    'Tác giả',
        'gi_author_val':    'Tlab  /  Park Yunjung ENTypoLab',
        'gi_source_lbl':    'Nguồn',
        'gi_source_val':    'Gong Yu Madang',
        'gi_license_lbl':   'Giấy phép',
        'gi_license_val':   'OFL (Open Font License)',
        'gi_font2_lbl':     'Phông tiếng Việt',
        'gi_font2_val':     'Quicksand',
        'gi_author2_lbl':   'Tác giả',
        'gi_author2_val':   'Andrew Paglinawan',
        'gi_source2_lbl':   'Nguồn',
        'gi_source2_val':   'Google Fonts',
        'gi_license2_lbl':  'Giấy phép',
        'gi_license2_val':  'OFL (Open Font License)',
        'gi_scroll_hint':   'W / S Cuộn    ESC Quay lại',

        'ach_popup_label':  'Thành tích!',

        'ach_first_run_name':        'Lần đầu tiên',
        'ach_first_run_desc':        'Bắt đầu chơi game lần đầu!',
        'ach_dist_100_name':         'Đạt 100m',
        'ach_dist_100_desc':         'Bạn đã chạy được 100m!',
        'ach_dist_500_name':         'Đạt 500m',
        'ach_dist_500_desc':         'Bạn đã chạy được 500m!',
        'ach_dist_1000_name':        'Đạt 1000m',
        'ach_dist_1000_desc':        'Bạn đã chạy được 1000m!',
        'ach_jelly_50_name':         'Vua Jelly',
        'ach_jelly_50_desc':         'Thu thập 50 Jelly trong một lượt!',
        'ach_combo_30_name':         'Bậc thầy combo',
        'ach_combo_30_desc':         'Đạt combo 30!',
        'ach_stage_street_name':     'Ra đường phố',
        'ach_stage_street_desc':     'Đến giai đoạn đường phố!',
        'ach_stage_playground_name': 'Đến sân chơi',
        'ach_stage_playground_desc': 'Đến giai đoạn sân chơi!',
        'ach_stage_home_name':       'Về nhà',
        'ach_stage_home_desc':       'Đến giai đoạn ngôi nhà!',
        'ach_shield_block_name':     'Chiến binh bất bại',
        'ach_shield_block_desc':     'Chặn chướng ngại vật bằng lá chắn!',

        # Thành tích mới (40)
        'ach_dist_2000_name':        'Vượt 2km',
        'ach_dist_2000_desc':        'Bạn đã chạy 2.000m!',
        'ach_dist_3000_name':        'Marathon 3km',
        'ach_dist_3000_desc':        'Bạn đã chạy 3.000m!',
        'ach_dist_5000_name':        'Chạy đường dài',
        'ach_dist_5000_desc':        'Bạn đã chạy 5.000m!',
        'ach_dist_10000_name':       'Huyền thoại',
        'ach_dist_10000_desc':       'Bạn đã chạy 10.000m!',
        'ach_stage_loop_name':       'Trở về trường',
        'ach_stage_loop_desc':       'Đi qua nhà rồi quay lại trường!',
        'ach_all_stages_name':       'Người khám phá',
        'ach_all_stages_desc':       'Đã ghé thăm cả 4 giai đoạn trong một lượt!',
        'ach_combo_10_name':         'Combo đầu tiên',
        'ach_combo_10_desc':         'Đạt combo 10!',
        'ach_combo_50_name':         'Vô địch combo',
        'ach_combo_50_desc':         'Đạt combo 50!',
        'ach_combo_100_name':        'Huyền thoại combo',
        'ach_combo_100_desc':        'Đạt combo 100!',
        'ach_max_multiplier_name':   'Bội số 4×',
        'ach_max_multiplier_desc':   'Đạt bội số điểm 4×!',
        'ach_food_100_run_name':     'Vua ăn',
        'ach_food_100_run_desc':     'Thu thập 100 món trong một lượt!',
        'ach_positive_30_name':      'Sành ăn lành mạnh',
        'ach_positive_30_desc':      'Ăn 30 món lành mạnh trong một lượt!',
        'ach_school_master_name':    'Bậc thầy trường học',
        'ach_school_master_desc':    'Ăn cả 3 món lành mạnh ở trường!',
        'ach_street_master_name':    'Bậc thầy tiện lợi',
        'ach_street_master_desc':    'Ăn cả 3 món lành mạnh ngoài đường!',
        'ach_playground_master_name':'Bậc thầy snack',
        'ach_playground_master_desc':'Ăn cả 3 món lành mạnh ở sân chơi!',
        'ach_home_master_name':      'Bậc thầy cơm nhà',
        'ach_home_master_desc':      'Ăn cả 3 món lành mạnh ở nhà!',
        'ach_all_pos_master_name':   'Thực đơn hoàn hảo',
        'ach_all_pos_master_desc':   'Ăn đủ 12 món lành mạnh trong một lượt!',
        'ach_veggie_lover_name':     'Bạn rau quả',
        'ach_veggie_lover_desc':     'Ăn táo, cà chua bi và khoai lang!',
        'ach_protein_set_name':      'Bộ đạm',
        'ach_protein_set_desc':      'Ăn sữa, sữa đậu nành và cá nướng!',
        'ach_pure_run_name':         'Thực đơn sạch',
        'ach_pure_run_desc':         'Chạy 1.000m mà không ăn đồ xấu!',
        'ach_no_cola_name':          'Không Cola',
        'ach_no_cola_desc':          'Chạy 1.000m mà không uống Cola!',
        'ach_junk_avoider_name':     'Tránh đồ ăn nhanh',
        'ach_junk_avoider_desc':     'Chạy 1.000m không hamburger/pizza/mì/cola!',
        'ach_snack_avoider_name':    'Từ chối đồ ngọt',
        'ach_snack_avoider_desc':    'Chạy 500m không kẹo/kẹo bông/kem/sô cô la!',
        'ach_water_first_name':      'Ngụm đầu tiên',
        'ach_water_first_desc':      'Uống nước đóng chai lần đầu!',
        'ach_water_5_run_name':      'Bổ sung nước',
        'ach_water_5_run_desc':      'Uống 5 chai nước trong một lượt!',
        'ach_water_10_run_name':     'Chuyên gia nước',
        'ach_water_10_run_desc':     'Uống 10 chai nước trong một lượt!',
        'ach_hydration_master_name': 'Cân bằng nước',
        'ach_hydration_master_desc': 'Giữ thanh nước ≥50% trong 1.000m!',
        'ach_thirst_survive_name':   'Vượt qua khát',
        'ach_thirst_survive_desc':   'Chạy thêm 100m trong khi khát!',
        'ach_hp_full_500_name':      'Không tổn thương',
        'ach_hp_full_500_desc':      'Chạy 500m với HP đầy!',
        'ach_last_breath_name':      'Hơi thở cuối',
        'ach_last_breath_desc':      'Chạy thêm 100m chỉ với 1 HP!',
        'ach_heart_collector_name':  'Sưu tầm tim',
        'ach_heart_collector_desc':  'Thu thập 3 tim trong một lượt!',
        'ach_first_skill_name':      'Kỹ năng đầu tiên',
        'ach_first_skill_desc':      'Kích hoạt kỹ năng lần đầu!',
        'ach_skill_master_name':     'Bậc thầy kỹ năng',
        'ach_skill_master_desc':     'Kích hoạt 5 kỹ năng trong một lượt!',
        'ach_invincible_clear_name': 'Vượt bất bại',
        'ach_invincible_clear_desc': 'Đi qua chướng ngại trong khi bất bại!',
        'ach_all_skills_name':       'Sưu tầm kỹ năng',
        'ach_all_skills_desc':       'Kích hoạt cả 4 loại kỹ năng trong một lượt!',
        'ach_shield_perfect_name':   'Tiết kiệm lá chắn',
        'ach_shield_perfect_desc':   'Chạy 1.000m với lá chắn bật!',
        'ach_score_5000_name':       '5.000 điểm',
        'ach_score_5000_desc':       'Đạt 5.000 điểm!',
        'ach_score_20000_name':      '20.000 điểm',
        'ach_score_20000_desc':      'Đạt 20.000 điểm!',
        'ach_score_50000_name':      'Bậc thầy 50.000 điểm',
        'ach_score_50000_desc':      'Đạt 50.000 điểm!',
        'ach_new_record_name':       'Kỷ lục mới!',
        'ach_new_record_desc':       'Lập kỷ lục điểm cao mới!',

        'skill_invincible_name':  'Bất bại!',
        'skill_slowdown_name':    'Chậm thời gian!',
        'skill_jelly_party_name': 'Tiệc Jelly!',
        'skill_score_blast_name': 'Điểm bùng nổ!',

        # Hiệu ứng món ăn — tên ngắn cho popup
        'effect_hp_or_score_short':  'HP +1',
        'effect_combo_plus_short':   'Combo +3',
        'effect_gauge_l_short':      'Thanh +20',
        'effect_gauge_s_short':      'Thanh +15',
        'effect_gauge_drain_short':  'Thanh -25',
        'effect_magnet_short_short': 'Nam châm!',
        'effect_score_bonus_short':  'Điểm thưởng!',
        'effect_score_l_short':      'Đại điểm!',
        'effect_rice_combo_short':   'Cơm bonus',
        'effect_hp_chance_short':    'Hồi HP!',
        'effect_shield_grant_short': 'Lá chắn!',
        'effect_cleanse_short':      'Đã giải độc!',
        'effect_combo_break_short':  'Combo bị phá',
        'effect_water_refill_short': 'Nước +20',
        'effect_water_drain_short':  'Nước -15',
        'effect_dizzy_short':        'Chóng mặt (Khóa nhảy đôi)',
        'effect_heavy_jump_short':   'Nhảy giảm',
        'effect_heavy_jump_l_short': 'Nhảy giảm',
        'effect_heavy_combo_short':  'Nhảy giảm + Combo dừng',
        'effect_vision_blur_short':  'Mờ tầm nhìn',
        'effect_slow_freeze_short':  'Đóng băng',
        'effect_sticky_short':       'Dính (Khóa trượt)',
        'effect_slide_short_short':  'Trượt giảm',
        'effect_gauge_freeze_short': 'Thanh dừng',
        'effect_score_mult_short':   'Điểm ×1.5!',
    },
}


def set_lang(lang_code):
    global _LANG
    _LANG = lang_code if lang_code in _STRINGS else 'ko'


def T(key):
    d = _STRINGS.get(_LANG, _STRINGS['ko'])
    return d.get(key, _STRINGS['ko'].get(key, key))
